### ISSUE TITLE
After upgrade to FW 2.21.1005 MiniProg4 cannot acquire CCG5 devices.

### ISSUE THREAD

**Issue by bslava** [Infineon/Firmware-loader#3]
**Prerequisites**

Can you reproduce the problem reliably? Yes

Did you check current release notes for known issues? Yes

**Description**:

After upgrade to FW 2.21.1005 MiniProg4 cannot acquire CCG5 devices (DMC devices are OK). Downgrading to 2.10.878 fixes the issue

**Steps to Reproduce:**

1. Upgrade to 2.21.1005 

2. Connect to CCG5 device

3. Try to read the device

**Expected Result:**
Reading device memory

**Actual Result:**
Error message stating that the device cannot be acquired.

**Frequency (1/1, 1/50, 1/100):**
1/1

**Build/Commit:**

 FW 2.21.1005

**Target:**

MiniProg4

**Host OS and Version:**

Windows 10

**Compiler:**

N/A

**Environment**

N/A

**Comment by ddka22** [comment]
Hello @bslava ,

Can you please answer the following questions so that we understand your issue better:
-  What use case are you using the CCG5 for?
-  What is the IDE/Programmer used? i.e PSoC Creator or PSoC Programmer or OpenOCD etc.

Please note that CCG5 is not officially supported by MiniProg4.

Regards,
Dheeraj

**Comment by bslava** [comment]
Hello Dheeraj,

Thank you for answering my question. Here are my answers:

- I tried to reprogram CCG5's FW.
- It was PSoC Programmer  3.29.1.4659.
- Do you know which programmer officially supports CCG5?

Thanks and Regards,
Slava

**Comment by rmbk19** [comment]
Hi Slava, 

Please use the [MiniProg3](https://www.cypress.com/documentation/development-kitsboards/cy8ckit-002-psoc-miniprog3-program-and-debug-kit) device to program CCGx devices in PSoC Programmer. 

Regards, 
Rakshith

**Comment by bslava** [comment]
Hi Rakshith,

If I understand correctly, the Miniprog4 firmware will not be fixed? Please note that PSoC Programmer 3.29.1.4659 silently updates MiniProg4 FW to 2.21.1005, and then the device loses some of its functionality. Maybe customers need to be warned before upgrading?

Regards,
Slava

**Comment by rmbk19** [comment]
Hi Slava, 

The [PSoC Programmer Release Notes](https://www.cypress.com/file/521481/download) does mention that programming CCG5 devices using MiniProg4 device is not guaranteed - 
![image](https://user-images.githubusercontent.com/57936462/122823169-a6fb2300-d2fc-11eb-84a6-fc13ab1f04f5.png)

That being said, we tested the programming of the CCG5 device with MiniProg 4 FW 2.21.1005 and we were able to successfully program the device. Can you please provide a screenshot of the PSoC Programmer with all the programming parameters set and also let us know the connections that you have made?

Regards, 
Rakshith

**Comment by bslava** [comment]
Thanks for continuing with this issue. Below are two examples:
programming with 2,10.878:
![image](https://user-images.githubusercontent.com/13033593/122858187-88a81e00-d322-11eb-97c8-bc096ae1a96f.png)
and with 2.2.1.1005:
![image](https://user-images.githubusercontent.com/13033593/122858357-d2910400-d322-11eb-9e88-17d95608bf8e.png)
I did not change anything except for MiniProg4 update.

**Comment by rmbk19** [comment]
Hi Slava, 

Can you please let me know if you have a 4.7 kohm pull-up resistor on the XRES line of the target device? If not, can you please try adding a pull-up resistor and let me know if that works? Without the pull-up resistor on the XRES line, MiniProg4 will not be able to acquire the device. Also, can you please share the schematics of your board?

Regards, 
Rakshith

**Comment by bslava** [comment]
Hi Rakshith,

Unfortunately, sharing the schematics is not easy for legal reasons.
As for XRES, we only have a 0.1uF capacitor as shown in the reference manual:
![image](https://user-images.githubusercontent.com/13033593/122993289-ce5ef800-d3af-11eb-93da-771edc90aeb6.png)
If you think that the absence of this 4.7k resistor can explain the difference between the behavior of versions 2.21 and 2.10, then I'll give it a try.

Regards,
Slava

**Comment by rmbk19** [comment]
Hi Slava, 

There were some changes in the recent update of MiniProg4 firmware which necessitates the use of a pull-up resistor on XRES. Yes, can you please try changing it to 4.7k and let us know if that works?

Regards, 
Rakshith

**Comment by bslava** [comment]
Hi Rakshith,

I'll try tomorrow to replace this resistor and let you know the results.
Below is LA trace of a failing SWD connection. Maybe it will be helpful.

Regards,
Slava

[CCG5_SWD.zip](https://github.com/Infineon/Firmware-loader/files/6724266/CCG5_SWD.zip)

**Comment by bslava** [comment]
Hi Rakshith,

Replacement of resistor and capacitor to the recommended values solved the issue.

Thanks,
Slava

**Comment by rmbk19** [comment]
Hi Slava, 

Thank you very much for the update! Glad it worked.

Regards, 
Rakshith
